version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/isonga
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  analytics:
    build: ./analytics-service
    ports:
      - "3001:3001"
    volumes:
      - ./analytics-service:/app
      - /app/node_modules
      - sqlite_data:/app/analytics.sqlite

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  sqlite_data: