apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-microservice
  template:
    metadata:
      labels:
        app: notification-microservice
    spec:
      containers:
      - name: notification-microservice
        image: isonga-notification:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: host
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: pass
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-microservice
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP